back/src/Entity/Production.php
<?php

namespace App\Entity;

use App\Repository\ProductionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductionRepository::class)]
class Production
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $original_title = null;

    #[ORM\Column(length: 300)]
    private ?string $slug = null;

    #[ORM\Column(length: 12, nullable: true)]
    private ?string $imdb_id = null;

    #[ORM\Column(length: 50)]
    private ?string $type = null;

    #[ORM\Column]
    private ?\DateTime $release_date = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tagline = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $synopsis = null;

    #[ORM\Column(nullable: true)]
    private ?float $rating = null;

    #[ORM\Column(length: 255)]
    private ?string $poster = null;

    #[ORM\Column(length: 255)]
    private ?string $backdrop = null;

    #[ORM\Column(length: 255)]
    private ?string $trailer = null;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'productions')]
    private Collection $tags;

    #[ORM\ManyToMany(targetEntity: Country::class, inversedBy: 'productions')]
    private Collection $countries;

    #[ORM\OneToMany(mappedBy: 'production', targetEntity: Credit::class, orphanRemoval: true)]
    private Collection $credits;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->countries = new ArrayCollection();
        $this->credits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getReleaseDate(): ?\DateTime
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTime $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getTagline(): ?string
    {
        return $this->tagline;
    }

    public function setTagline(?string $tagline): self
    {
        $this->tagline = $tagline;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(?float $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getBackdrop(): ?string
    {
        return $this->backdrop;
    }

    public function setBackdrop(string $backdrop): self
    {
        $this->backdrop = $backdrop;

        return $this;
    }

    public function getTrailer(): ?string
    {
        return $this->trailer;
    }

    public function setTrailer(string $trailer): self
    {
        $this->trailer = $trailer;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    /**
     * @return Collection<int, Country>
     */
    public function getCountries(): Collection
    {
        return $this->countries;
    }

    public function addCountry(Country $country): self
    {
        if (!$this->countries->contains($country)) {
            $this->countries->add($country);
        }

        return $this;
    }

    public function removeCountry(Country $country): self
    {
        $this->countries->removeElement($country);

        return $this;
    }

    /**
     * @return Collection<int, Credit>
     */
    public function getCredits(): Collection
    {
        return $this->credits;
    }

    public function addCredit(Credit $credit): self
    {
        if (!$this->credits->contains($credit)) {
            $this->credits->add($credit);
            $credit->setProduction($this);
        }

        return $this;
    }

    public function removeCredit(Credit $credit): self
    {
        if ($this->credits->removeElement($credit)) {
            // set the owning side to null (unless already changed)
            if ($credit->getProduction() === $this) {
                $credit->setProduction(null);
            }
        }

        return $this;
    }

    public function getOriginalTitle(): ?string
    {
        return $this->original_title;
    }

    public function setOriginalTitle(string $original_title): self
    {
        $this->original_title = $original_title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImdbId(): ?string
    {
        return $this->imdb_id;
    }

    public function setImdbId(?string $imdb_id): self
    {
        $this->imdb_id = $imdb_id;

        return $this;
    }
}

back/src/Form/ProductionType.php
<?php

namespace App\Form;

use App\Entity\Production;
use App\Service\TextFormatService;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductionType extends AbstractType
{
    private $TextFormatService;

    public function __construct(TextFormatService $TextFormatService)
    {
        $this->TextFormatService = $TextFormatService;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label'     => 'Titre',
                'attr'      => [
                    'placeholder' => 'Titre'
                ]
            ])
            ->add('original_title', TextType::class, [
                'label'     => 'Titre original',
                'attr'      => [
                    'placeholder' => 'Titre original'
                ]
            ])
            ->add('slug', HiddenType::class, [
                'empty_data'    => 'test',
            ])
            ->add('imdb_id', HiddenType::class, [
                'empty_data'    => null
            ])
            ->add('type', ChoiceType::class, [
                'label'     => 'Type',
                'choices'   => [
                    'Film'      => 'movie',
                    'Série'     => 'tv'
                ]
            ])
            ->add('release_date', DateType::class, [
                'label'     => 'Date de sortie / première diffusion',
                'widget'    => 'single_text',
                'format'    => 'yyyy-MM-dd',
                'attr'      => [
                    'placeholder' => 'Date de sortie'
                ]
            ])
            ->add('duration', NumberType::class, [
                'label'     => 'Durée',
                'attr'      => [
                    'placeholder' => 'Durée',
                    'help'        => 'Durée en minutes'
                ]
            ])
            ->add('tagline', TextType::class, [
                'label'     => 'Slogan',
                'attr'      => [
                    'placeholder' => 'Slogan'
                ]
            ])
            ->add('synopsis', TextareaType::class, [
                'label'     => 'Synopsis',
                'attr'      => [
                    'placeholder' => 'Synopsis'
                ]
            ])
            ->add('poster', HiddenType::class, [
                'empty_data'    => 'https://via.placeholder.com/300x450.png?text=Pas+d\'image+disponible'
            ])
            ->add('backdrop', HiddenType::class, [
                'empty_data'    => 'https://via.placeholder.com/450x300.png?text=Pas+d\'image+disponible'
            ])
            ->add('trailer', HiddenType::class, [
                'empty_data'    => 'https://www.youtube.com/embed/0W0Wc1E8ffk'
            ])
            /* ->add('tags')
            ->add('countries') */;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Production::class,
        ]);
    }
}

back/src/Controller/ProductionController.php
<?php

namespace App\Controller;

use App\Entity\Production;
use App\Form\ProductionType;
use App\Repository\ProductionRepository;
use App\Service\ProductionRetrievalService;
use App\Service\TextFormatService;
use DateTime;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/productions')]
class ProductionController extends AbstractController
{
    #[Route('/', name: 'app_production_index', methods: ['GET'])]
    public function index(ProductionRepository $productionRepository): Response
    {
        return $this->render('production/index.html.twig', [
            'productions' => $productionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_production_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProductionRetrievalService $productionRetrievalService, ProductionRepository $productionRepository): Response
    {
        $title = $request->request->get('title');

        if ($title) {
            $searchResults = $productionRetrievalService->search($title);
            return $this->renderForm('production/new.html.twig', [
                'searchResults' => $searchResults,
            ]);
        }

        return $this->render('production/new.html.twig');
    }

    #[Route('/add', name: 'app_production_add', methods: ['GET', 'POST'])]
    public function add(
        Request $request,
        TextFormatService $TextFormatService,
        ProductionRepository $productionRepository
    ): Response {
        $selectedProduction = $request->request->get('selected_production');
        $production = new Production();
        if (isset($selectedProduction['title'])) {
            $production->setTitle($selectedProduction['title'])
                ->setOriginalTitle($selectedProduction['original_title'])
                ->setSlug($TextFormatService->slugify($selectedProduction['title']))
                ->setImdbId($selectedProduction['imdb_id'] ?? 'test')
                ->setType($selectedProduction['media_type'] === 'movie' ? 'Film' : 'Série')
                ->setReleaseDate(new DateTime($selectedProduction['release_date']))
                ->setDuration($selectedProduction['duration'] ?? 77)
                ->setTagline($selectedProduction['tagline'] ?? 'test')
                ->setSynopsis($selectedProduction['summary'])
                ->setRating($selectedProduction['rating'] ?? 0.1)
                ->setPoster($selectedProduction['poster_path'] ?? 'test')
                ->setBackdrop($selectedProduction['backdrop_path'] ?? 'test')
                ->setTrailer($selectedProduction['trailer'] ?? 'test');
        }

        $form = $this->createForm(ProductionType::class, $production);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productionRepository->save($production, true);

            return $this->redirectToRoute('app_production_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('production/add.html.twig', [
            'production' => $production,
            'selectedProduction' => $selectedProduction,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/medias', name: 'app_production_medias', methods: ['POST'])]
    public function medias(Request $request, Production $production, ProductionRepository $productionRepository): Response
    {
        $medias = $request->request->all();
        //$production->setMedias($medias);
        $productionRepository->save($production, true);

        return $this->redirectToRoute('app_production_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app_production_show', methods: ['GET'])]
    public function show(Production $production): Response
    {
        return $this->render('production/show.html.twig', [
            'production' => $production,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_production_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Production $production, ProductionRepository $productionRepository): Response
    {
        $form = $this->createForm(ProductionType::class, $production);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productionRepository->save($production, true);

            return $this->redirectToRoute('app_production_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('production/edit.html.twig', [
            'production' => $production,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_production_delete', methods: ['POST'])]
    public function delete(Request $request, Production $production, ProductionRepository $productionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $production->getId(), $request->request->get('_token'))) {
            $productionRepository->remove($production, true);
        }

        return $this->redirectToRoute('app_production_index', [], Response::HTTP_SEE_OTHER);
    }
}

back/templates/production/_delete_form.html.twig
<form method="post" action="{{ path('app_production_delete', {'id': production.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ production.id) }}">
	<button class="btn btn-primary">Delete</button>
</form>

back/templates/production/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<div class="d-flex justify-content-end mb-3">
	<button class="btn btn-primary">{{ button_label|default('Valider') }}</button>
</div>
{{ form_end(form) }}

back/templates/production/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un programme
{% endblock %}

{% block body %}
	<h1>Ajouter un programme</h1>

	{{ include('production/_form.html.twig') }}

{% endblock %}

back/templates/production/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Production{% endblock %}

{% block body %}
    <h1>Edit Production</h1>

    {{ include('production/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_production_index') }}">back to list</a>

    {{ include('production/_delete_form.html.twig') }}
{% endblock %}

back/templates/production/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Production index
{% endblock %}

{% block body %}
	<h1>Production index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Title</th>
				<th>Original title</th>
				<th>Slug</th>
				<th>IMDB id</th>
				<th>Type</th>
				<th>Release_date</th>
				<th>Duration</th>
				<th>Tagline</th>
				<th>Synopsis</th>
				<th>Rating</th>
				<th>Poster</th>
				<th>Backdrop</th>
				<th>Trailer</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for production in productions %}
				<tr>
					<td>{{ production.id }}</td>
					<td>{{ production.title }}</td>
					<td>{{ production.originalTitle }}</td>
					<td>{{ production.slug }}</td>
					<td>{{ production.imdbId }}</td>
					<td>{{ production.type }}</td>
					<td>{{ production.releaseDate ? production.releaseDate|date('d/m/Y') : '' }}</td>
					<td>{{ production.duration }}</td>
					<td>{{ production.tagline }}</td>
					<td>{{ production.synopsis }}</td>
					<td>{{ production.rating }}</td>
					<td>{{ production.poster }}</td>
					<td>{{ production.backdrop }}</td>
					<td>{{ production.trailer }}</td>
					<td>
						<a href="{{ path('app_production_show', {'id': production.id}) }}">show</a>
						<a href="{{ path('app_production_edit', {'id': production.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="12">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_production_new') }}">Create new</a>
{% endblock %}

back/templates/production/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un programme
{% endblock %}

{% block body %}
	<h1>Ajouter un programme</h1>


	<form action="" method="post">
		<div class="form-floating mb-3">
			<input type="text" required="required" name="title" placeholder="Titre du film" class="form-control">
			<label class="form-label required">Titre</label>
		</div>
		<div class="d-flex justify-content-end mb-3">
			<input type="submit" value="Rechercher" href="{{ path('app_production_new') }}" class="btn btn-primary">
		</div>
	</form>

	{% if searchResults is defined %}
		{# <div class="row row-cols-1 row-cols-md-2 g-4"> #}
		{% for searchResult in searchResults %}
			<div class="col">
				<div class="card mb-3">
					<div class="row g-0">
						<div class="col-md-4">
							{% if searchResult.poster_path is not empty %}
								<img src="{{ searchResult.poster_path }}" class="img-fluid rounded-start" alt="...">
							{% else %}
								<img src="https://via.placeholder.com/600x900" class="img-fluid rounded-start" alt="...">
							{% endif %}
						</div>
						<div class="col-md-8 d-flex flex-column align-content-between">
							<div class="card-body">
								<h5 class="card-title">{{ searchResult.title }}</h5>
								<h6 class="card-subtitle mb-2 text-muted">{{ searchResult.original_title }}</h6>
								{% if searchResult.summary|length > 191 %}
									<p class="card-text">{{ searchResult.summary|slice(0,192) }}
										[...]</p>
								{% else %}
									<p class="card-text">{{ searchResult.summary }}</p>
								{% endif %}
								<p class="card-text">
									<small class="text-muted">
										{% if searchResult.media_type == 'tv' %}
											<i class="bi bi-tv"></i>
											Série
										{% elseif searchResult.media_type == 'movie' %}
											<i class="bi bi-film"></i>
											Film
										{% else %}
											<i class="bi bi-question-lg"></i>
											Inconnu
										{% endif %}
										<span>
											|
										</span>
										{{ searchResult.release_date|date('Y') }}
										<span>
											|
										</span>
										{{ searchResult.country }}
									</small>
								</p>
							</div>
							<form action="{{ path('app_production_add') }}" method="post">
								<input type="hidden" name="selected_production[title]" value="{{ searchResult.title }}">
								<input type="hidden" name="selected_production[original_title]" value="{{ searchResult.original_title }}">
								<input type="hidden" name="selected_production[imdb_id]" value="{{ searchResult.imdb_id }}">
								<input type="hidden" name="selected_production[media_type]" value="{{ searchResult.media_type }}">
								<input type="hidden" name="selected_production[summary]" value="{{ searchResult.summary }}">
								<input type="hidden" name="selected_production[poster_path]" value="{{ searchResult.poster_path }}">
								<input type="hidden" name="selected_production[media_type]" value="{{ searchResult.media_type }}">
								<input type="hidden" name="selected_production[release_date]" value="{{ searchResult.release_date }}">
								<input type="hidden" name="selected_production[country]" value="{{ searchResult.country }}">
								<input type="hidden" name="selected_production[tmdb_id]" value="{{ searchResult.tmdb_id }}">
								<div class="d-flex justify-content-end" style="padding: 16px;">
									<input type="submit" value="Selectionner" href="{{ path('app_production_add') }}" class="btn btn-primary">
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
		{# </div> #}
	{% endif %}
{% endblock %}

back/templates/production/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Production{% endblock %}

{% block body %}
    <h1>Production</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ production.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ production.title }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ production.type }}</td>
            </tr>
            <tr>
                <th>Release_date</th>
                <td>{{ production.releaseDate ? production.releaseDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ production.duration }}</td>
            </tr>
            <tr>
                <th>Tagline</th>
                <td>{{ production.tagline }}</td>
            </tr>
            <tr>
                <th>Synopsis</th>
                <td>{{ production.synopsis }}</td>
            </tr>
            <tr>
                <th>Rating</th>
                <td>{{ production.rating }}</td>
            </tr>
            <tr>
                <th>Poster</th>
                <td>{{ production.poster }}</td>
            </tr>
            <tr>
                <th>Backdrop</th>
                <td>{{ production.backdrop }}</td>
            </tr>
            <tr>
                <th>Trailer</th>
                <td>{{ production.trailer }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_production_index') }}">back to list</a>

    <a href="{{ path('app_production_edit', {'id': production.id}) }}">edit</a>

    {{ include('production/_delete_form.html.twig') }}
{% endblock %}